name: thesis-temporal-deid
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - opencv>=4.5.0
  - pillow>=8.0.0
  - tqdm>=4.60.0
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - scikit-image>=0.19.0
  - imageio>=2.15.0
  - mediapipe>=0.8.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - pyyaml>=6.0
  - fastapi>=0.95.0
  - uvicorn>=0.20.0
  - pip:
    - pathlib2>=2.3.0
    - requests>=2.28.0
