# -------------------------
# Model configuration
# -------------------------
model:
  checkpoint_path: samurai/sam2/checkpoints/sam2.1_hiera_base_plus.pt
  device: cuda
  model_type: hiera_base_plus    # Update depending on what SAMURAI code expects

# -------------------------
# Inference settings
# -------------------------
inference:
  frame_stride: 6
  min_area: 100
  suppress_bottom_text: true

# -------------------------
# Output settings
# -------------------------
output:
  save_overlay: true
  overlay_alpha: 0.5
  save_frames: true
