# # -------------------------
# # Model configuration
# # -------------------------
# model:
#   checkpoint_path: tsp_sam/model_checkpoint/best_checkpoint.pth  # TSP-SAM model weights
#   device: cuda                                                   # Use 'cuda' or 'cpu'
#   channel: 32                                                    # Number of channels for TSP-SAM (default)

# # -------------------------
# # Inference settings
# # -------------------------
# inference:
#   frame_stride: 2                    # Process every frame for TED talk
#   min_area: 1000                    # Lowered minimum area to reduce filtering of valid masks
#   suppress_bottom_text: true         # Zero out bottom 10% of mask to remove subtitles/watermarks
#   dynamic_kernel_divisor: 100       # Dynamic kernel size based on mask resolution
#   adaptive_percentile: 96           # Slightly relaxed threshold to allow more true positives

# # -------------------------
# # Output control
# # -------------------------
# output:
#   save_overlay: true                # Save composite overlay images
#   overlay_alpha: 0.5                # Transparency for overlay
#   save_frames: true                 # Save raw frames alongside outputs

# # -------------------------
# # SAM-related config (for fusion with TSP-SAM)
# # -------------------------
# compare_sam: true                   # Use bounding box from TSP-SAM to prompt SAM
# fusion_method: "union"             # Mask fusion strategy: "union", "intersection", or "tsp_only"

# # -------------------------
# # SAM Checkpoint Info
# # -------------------------
# sam_checkpoint: "temporal/checkpoints/sam_vit_b_01ec64.pth"  # Pretrained SAM checkpoint
# sam_model_type: "vit_b"                                      # SAM backbone: vit_b / vit_l / vit_h

# # -------------------------
# # Dataset mode
# # -------------------------
# dataset:
#   mode: ted

# fusion:
#   enable_sam: true
#   enable_pose: true       # <-- Add this


# -------------------------
# Model configuration
# -------------------------
model:
  checkpoint_path: tsp_sam/model_checkpoint/best_checkpoint.pth  # TSP-SAM model weights
  device: cuda                                                   # Use 'cuda' or 'cpu'
  channel: 32                                                    # Default TSP-SAM channels

# -------------------------
# Inference settings
# -------------------------
inference:
  frame_stride: 1
  min_area: 800
  suppress_bottom_text: true
  dynamic_kernel_divisor: 80
  adaptive_percentile: 95
  temporal_smoothing: true
  reset_memory_every: 12

  # NEW: Pose filtering control
  min_keypoints: 10                   # Skip weak OpenPose results 8
  relaxation_factor: 0.4             # More relaxed for vertical frames
  pose_thresh_percentile: 20        # Use lower percentile (more inclusive) 10
  max_dynamic_thresh: 160000         # NEW: cap threshold to not exceed full-body limits

# -------------------------
# Output control
# -------------------------
output:
  save_overlay: true
  overlay_alpha: 0.5
  save_frames: true

# -------------------------
# SAM-related config (for fusion with TSP-SAM)
# -------------------------
compare_sam: true
# fusion_method: "union"             # TSP + SAM + Pose union fusion
fusion_method: "tsp+pose"  # More conservative

# -------------------------
# SAM Checkpoint Info
# -------------------------
sam_checkpoint: "temporal/checkpoints/sam_vit_b_01ec64.pth"
sam_model_type: "vit_b"

# -------------------------
# Dataset mode
# -------------------------
dataset:
  mode: ted

# -------------------------
# Debugging & Evaluation
# -------------------------
debug:
  save_csv: true

# -------------------------
# Fusion Control
# -------------------------
# fusion:
#   enable_sam: true
#   enable_pose: true


fusion:
  enable_sam: true
  enable_pose: true
  pose_area_ratio_thresh: 10      # Filter pose if it's too large relative to TSP
  tsp_area_min_valid: 500         # Minimum TSP area to consider pose too large




model:
  checkpoint_path: tsp_sam/model_checkpoint/best_checkpoint.pth
  backbone_path: tsp_sam/model_checkpoint/pvt_v2_b5.pth


# postprocess:
#   min_area: 1550
#   large_area_threshold: 50000
#   min_extent: 0.15
#   dilation_iters: 1


# postprocess:
#   min_area: 1200                 # Accept smaller valid masks (e.g., limbs, objects)
#   large_area_threshold: 50000    # Lowered large region cutoff for DAVIS
#   min_extent: 0.15           # Allow less compact masks (thin silhouettes)
#   dilation_iters: 1              # Slight dilation to recover structure
#   use_solidity_filter: true
#   edge_fade: true
#   iou_check: true
#   border_margin: 0.05


postprocess:
  min_area: 1200                # Default area threshold (scaled by resolution)
  large_area_threshold: 50000   # Fast accept if region is extremely large
  min_extent: 0.15              # Minimum ratio of filled pixels in bbox
  dilation_iters: 1            # Final dilation after postprocessing
  use_solidity_filter: true    # Enable convexity filtering for irregular blobs
  edge_fade: true              # Smooth mask borders visually in overlay
  iou_check: true              # Warn if frame deviates from temporal mask
  max_aspect_ratio: 6.0        # Upper bound on blob width/height ratio
  min_solidity: 0.25           # Minimum solidity (convexity) for valid region
  border_margin_pct: 0.03      # Mask border strip removal (e.g., TED stage borders)
  extent_suppression: true     # Enable extra extent+area based suppression
