# -------------------------
# Model configuration
# -------------------------
model:
  checkpoint_path: tsp_sam/model_checkpoint/best_checkpoint.pth  # TSP-SAM model weights
  device: cuda                                                   # Use 'cuda' or 'cpu'
  channel: 32                                                    # Number of channels for TSP-SAM (default)

# -------------------------
# Inference settings
# -------------------------
inference:
  frame_stride: 6                     # Process every 6th frame
  min_area: 100                     # Minimum pixel area for a valid mask
  suppress_bottom_text: true         # Zero out bottom 10% of mask to remove subtitles/watermarks

# -------------------------
# Output control
# -------------------------
output:
  save_overlay: true                # Save composite overlay images
  overlay_alpha: 0.5                # Transparency for overlay
  save_frames: true                 # Save raw frames alongside outputs

# -------------------------
# SAM-related config (for fusion with TSP-SAM)
# -------------------------
compare_sam: true                   # If true, SAM will be invoked with bounding box from TSP-SAM
fusion_method: "union"             # Mask fusion strategy: "union", "intersection", or "tsp_only"

# -------------------------
# SAM Checkpoint Info
# -------------------------
sam_checkpoint: "temporal/checkpoints/sam_vit_b_01ec64.pth"  # Pretrained SAM checkpoint
sam_model_type: "vit_b"                                      # SAM backbone: vit_b / vit_l / vit_h
