model:
  checkpoint_path: tsp_sam/model_checkpoint/best_checkpoint.pth
  device: cuda
  channel: 32

inference:
  frame_stride: 6
  min_area: 400
  suppress_bottom_text: true

output:
  save_overlay: true
  overlay_alpha: 0.5
  save_frames: true

# New additions
compare_sam: true
fusion_method: "union"
# sam_checkpoint: "checkpoints/sam_vit_b.pth"
sam_checkpoint: "temporal/checkpoints/sam_vit_b_01ec64.pth"
sam_model_type: "vit_b"
