dataset:
  name: "ted_talks"
  type: "presentation"
  description: "TED talk videos optimized for speaker-centric de-identification with controlled environments"
  
  # Core pipeline parameters
  processing:
    max_frames: null  # null = process all frames
    temporal_window_size: 7  # TSP-SAM temporal window
    confidence_threshold: 0.6  # Lower threshold for TED talks
    mask_quality_threshold: 0.5  # More lenient for stage lighting
    
  # Model-specific configurations
  tsp_sam:
    input_sizes: [352, 320, 256]  # Paper-validated square dimensions
    temporal_processing: true
    fallback_to_single_frame: true
    checkpoint_path: "tsp_sam_official/model_checkpoint/pvt_v2_b5.pth"
    fallback_checkpoint: "tsp_sam_official/model_checkpoint/best_checkpoint.pth"
    adaptive_threshold: true  # Enable dynamic threshold adjustment
    
  samurai:
    person_detection: true
    confidence_threshold: 0.4  # Lower threshold for stage lighting
    max_persons: 30  # TED talks usually have 1-3 people
    checkpoint_path: "samurai_official/sam2/checkpoints/sam2.1_hiera_large.pt"
    enable_caching: true  # Enable frame caching
    
  maskanyone:
    deidentification_strength: "strong"  # Strong de-identification for public figures
    preserve_identity: false
    checkpoint_path: "maskanyone/worker/masking/mask_renderer.py"
    
  # TED-specific optimizations
  ted_optimizations:
    stage_lighting_adaptation: true
    speaker_prioritization: true
    background_subtraction: true
    motion_sensitivity: "high"
    professional_setting: true
    controlled_environment: true
    
  # Output settings
  output:
    save_original_frames: true
    save_deidentified_frames: true
    save_masks: false
    save_performance_report: true
    frame_format: "jpg"
    quality: 95
    
  # Performance settings
  performance:
    enable_cuda: true
    batch_size: 1
    memory_efficient: true
    debug_mode: false
    
  # Cache settings
  cache:
    enable_frame_cache: true
    max_cache_size: 500  # Smaller cache for TED talks
    cache_ttl: 1800  # 30 minutes
    
  # Fallback strategies
  fallback:
    tsp_sam_fallback: "single_frame"
    samurai_fallback: "lower_threshold"
    maskanyone_fallback: "strong_deidentification"
