dataset:
  name: "tragic_talkers"
  type: "conversation"
  description: "Shakespearean conversational videos with high-resolution capture - optimized for dramatic performances and emotional expressions"
  
  # Core pipeline parameters
  processing:
    max_frames: null  # null = process all frames (150 frames)
    temporal_window_size: 5  # Reduced for conversational content
    confidence_threshold: 0.3  # Lowered for better detection on dramatic content
    mask_quality_threshold: 0.4  # Lowered quality threshold for better detection
    chunk_size: 25  # Process in chunks for memory efficiency
    
  # Model-specific configurations
  tsp_sam:
    input_sizes: [1024, 896, 768]  # Optimized for high-res content
    temporal_processing: true
    fallback_threshold: 0.2  # Lower fallback threshold
    min_mask_area: 100  # Smaller minimum area for dramatic content
    
  samurai:
    enabled: true
    confidence_threshold: 0.25  # Lower confidence for better detection
    max_masks: 10  # Allow more masks for complex scenes
    
  mask_any_one:
    enabled: true
    confidence_threshold: 0.3  # Lower threshold for better detection
    max_masks: 8
    
  # Output configuration
  output:
    save_frames: true
    save_masks: true
    save_videos: true
    video_fps: 10
    deidentification_method: "blurring"
    blur_strength: 15
    
  # Performance optimization
  optimization:
    use_gpu: true
    batch_processing: false
    memory_efficient: true
    temporal_smoothing: true
