dataset:
  name: "tragic_talkers"
  type: "conversation"
  description: "Conversational videos with natural lighting and emotional content - optimized for interviews and emotional expressions"
  
  # Core pipeline parameters
  processing:
    max_frames: null  # null = process all frames
    temporal_window_size: 7  # TSP-SAM temporal window
    confidence_threshold: 0.65  # Balanced threshold
    mask_quality_threshold: 0.6  # Standard quality
    
  # Model-specific configurations
  tsp_sam:
    input_sizes: [352, 320, 256]  # Paper-validated square dimensions
    temporal_processing: true
    fallback_to_single_frame: true
    checkpoint_path: "tsp_sam_official/model_checkpoint/pvt_v2_b5.pth"
    fallback_checkpoint: "tsp_sam_official/model_checkpoint/best_checkpoint.pth"
    adaptive_threshold: true  # Enable dynamic threshold adjustment
    
  samurai:
    person_detection: true
    confidence_threshold: 0.5  # Standard threshold
    max_persons: 50  # Moderate number of people
    checkpoint_path: "samurai_official/sam2/checkpoints/sam2.1_hiera_large.pt"
    enable_caching: true  # Enable frame caching
    
  maskanyone:
    deidentification_strength: "medium"  # Balanced de-identification
    preserve_identity: false
    checkpoint_path: "maskanyone/worker/masking/mask_renderer.py"
    
  # Tragic talkers specific optimizations
  tragic_optimizations:
    natural_lighting: true
    emotional_content: true
    conversational_setting: true
    moderate_motion: true
    interview_setting: true
    expressive_gestures: true
    varied_backgrounds: true
    
  # Output settings
  output:
    save_original_frames: true
    save_deidentified_frames: true
    save_masks: false
    save_performance_report: true
    frame_format: "jpg"
    quality: 95
    
  # Performance settings
  performance:
    enable_cuda: true
    batch_size: 1
    memory_efficient: true
    debug_mode: false
    
  # Cache settings
  cache:
    enable_frame_cache: true
    max_cache_size: 1500  # Medium cache size
    cache_ttl: 5400  # 1.5 hours
    
  # Fallback strategies
  fallback:
    tsp_sam_fallback: "single_frame"
    samurai_fallback: "lower_threshold"
    maskanyone_fallback: "balanced_deidentification"
